version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
